
server_tokens off;
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name weiyang.42.fr;

    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;

        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS on;
    }

    location /adminer {
        # 1. Dynamic topology decoupling via Docker DNS
        resolver 127.0.0.11 valid=30s;
        set $upstream_adminer adminer;

        # 2. Forward the request to the Adminer container using FastCGI over port 9000
        include fastcgi_params;
        fastcgi_pass $upstream_adminer:9000;
        fastcgi_index index.php;
        
        # 3. Specify the absolute path to the entry script inside the Adminer container
        fastcgi_param SCRIPT_FILENAME /var/www/html/adminer/index.php;
        fastcgi_param HTTPS on;
    }

    location /resume/ {
        alias /var/www/static/resume/;
        index index.html;
    }

    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
}