server_tokens off;

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name weiyang.42.fr;

    # 1. 👑 密码学底座全量提权：强行锁死 TLSv1.2，仅允许纯净、刚性的 TLSv1.3 独占内存空间！
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;
    ssl_protocols TLSv1.3;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # 2. 👑 WordPress 动态计算网格路由
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;

        # 🎯 物理对齐：死死咬合我们在 www.conf 中硬化改写的 9001 端口！
        fastcgi_pass wordpress:9001;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS on;
    }

    # 3. 👑 Adminer 高性能动态拓扑路由
    location /adminer {
        # 利用 Docker 内部 DNS 解析器，完美阻断容器冷启动时的时序依赖死锁
        resolver 127.0.0.11 valid=30s;
        set $upstream_adminer adminer;

        # 🎯 物理对齐：死死咬合我们在 Adminer Dockerfile 中硬化改写的 9002 端口！
        # 👑 核心加固：必须先 include 常规参数，确保基础 VFS 环境变量全量引渡
        include fastcgi_params;
        fastcgi_pass $upstream_adminer:9002;
        
        # 👑 绝对路径重映射：强行修正 FastCGI 内部的运行期主权指针
        fastcgi_param SCRIPT_FILENAME /var/www/html/adminer/index.php;
        fastcgi_param HTTPS on;
    }

    # 4. 👑 静态简历资产只读卸载
    location /resume/ {
        alias /var/www/static/resume/;
        index index.html;
    }

    # 5. 👑 工业级 HTTP 响应头防渗透硬化
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
}